ALTER TABLE service_overrides 
ADD COLUMN IF NOT EXISTS refill BOOLEAN DEFAULT NULL,
ADD COLUMN IF NOT EXISTS cancel BOOLEAN DEFAULT NULL,
ADD COLUMN IF NOT EXISTS dripfeed BOOLEAN DEFAULT NULL,
ADD COLUMN IF NOT EXISTS service_type TEXT DEFAULT NULL;
