// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_v2.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const generateAPIKey = `-- name: GenerateAPIKey :exec
UPDATE users SET api_key = $1 WHERE id = $2
`

type GenerateAPIKeyParams struct {
	ApiKey pgtype.Text `json:"api_key"`
	ID     int32       `json:"id"`
}

func (q *Queries) GenerateAPIKey(ctx context.Context, arg GenerateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, generateAPIKey, arg.ApiKey, arg.ID)
	return err
}

const getOrderStatusForAPI = `-- name: GetOrderStatusForAPI :one
SELECT amount_cents, COALESCE(start_count, 0)::int as start_count, status, COALESCE(remains, 0)::int as remains
FROM orders WHERE id = $1 AND user_id = $2
`

type GetOrderStatusForAPIParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetOrderStatusForAPIRow struct {
	AmountCents int32  `json:"amount_cents"`
	StartCount  int32  `json:"start_count"`
	Status      string `json:"status"`
	Remains     int32  `json:"remains"`
}

func (q *Queries) GetOrderStatusForAPI(ctx context.Context, arg GetOrderStatusForAPIParams) (GetOrderStatusForAPIRow, error) {
	row := q.db.QueryRow(ctx, getOrderStatusForAPI, arg.ID, arg.UserID)
	var i GetOrderStatusForAPIRow
	err := row.Scan(
		&i.AmountCents,
		&i.StartCount,
		&i.Status,
		&i.Remains,
	)
	return i, err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one
SELECT u.id, COALESCE(w.balance, 0)::int as balance, COALESCE(u.currency, 'INR')::text as currency 
FROM users u 
LEFT JOIN wallets w ON u.id = w.user_id 
WHERE u.api_key = $1 AND u.api_key_enabled = TRUE
`

type GetUserByAPIKeyRow struct {
	ID       int32  `json:"id"`
	Balance  int32  `json:"balance"`
	Currency string `json:"currency"`
}

func (q *Queries) GetUserByAPIKey(ctx context.Context, apiKey pgtype.Text) (GetUserByAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKey, apiKey)
	var i GetUserByAPIKeyRow
	err := row.Scan(&i.ID, &i.Balance, &i.Currency)
	return i, err
}

const insertAPIOrder = `-- name: InsertAPIOrder :one
INSERT INTO orders (user_id, service_id, quantity, amount_cents, status, created_at, link) 
VALUES ($1, $2, $3, $4, $5, NOW(), $6) RETURNING id
`

type InsertAPIOrderParams struct {
	UserID      int32       `json:"user_id"`
	ServiceID   string      `json:"service_id"`
	Quantity    int32       `json:"quantity"`
	AmountCents int32       `json:"amount_cents"`
	Status      string      `json:"status"`
	Link        pgtype.Text `json:"link"`
}

func (q *Queries) InsertAPIOrder(ctx context.Context, arg InsertAPIOrderParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertAPIOrder,
		arg.UserID,
		arg.ServiceID,
		arg.Quantity,
		arg.AmountCents,
		arg.Status,
		arg.Link,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateAPIOrderStatusFailed = `-- name: UpdateAPIOrderStatusFailed :exec
UPDATE orders SET status = 'failed' WHERE id = $1
`

func (q *Queries) UpdateAPIOrderStatusFailed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateAPIOrderStatusFailed, id)
	return err
}

const updateAPIOrderStatusSubmitted = `-- name: UpdateAPIOrderStatusSubmitted :exec
UPDATE orders SET provider_resp = $1, provider_order_id = $2, status = $3 WHERE id = $4
`

type UpdateAPIOrderStatusSubmittedParams struct {
	ProviderResp    []byte      `json:"provider_resp"`
	ProviderOrderID pgtype.Text `json:"provider_order_id"`
	Status          string      `json:"status"`
	ID              int32       `json:"id"`
}

func (q *Queries) UpdateAPIOrderStatusSubmitted(ctx context.Context, arg UpdateAPIOrderStatusSubmittedParams) error {
	_, err := q.db.Exec(ctx, updateAPIOrderStatusSubmitted,
		arg.ProviderResp,
		arg.ProviderOrderID,
		arg.Status,
		arg.ID,
	)
	return err
}
