// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCatalogService = `-- name: CreateCatalogService :one
INSERT INTO pablo_catalog (
    name, variant_name, sell_price_inr, platform, category, provider_id, provider_service_id, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, name, variant_name, sell_price_inr, platform, category, is_active, provider_id, provider_service_id, created_at, updated_at
`

type CreateCatalogServiceParams struct {
	Name              string         `json:"name"`
	VariantName       pgtype.Text    `json:"variant_name"`
	SellPriceInr      pgtype.Numeric `json:"sell_price_inr"`
	Platform          pgtype.Text    `json:"platform"`
	Category          pgtype.Text    `json:"category"`
	ProviderID        pgtype.Text    `json:"provider_id"`
	ProviderServiceID pgtype.Text    `json:"provider_service_id"`
	IsActive          pgtype.Bool    `json:"is_active"`
}

func (q *Queries) CreateCatalogService(ctx context.Context, arg CreateCatalogServiceParams) (PabloCatalog, error) {
	row := q.db.QueryRow(ctx, createCatalogService,
		arg.Name,
		arg.VariantName,
		arg.SellPriceInr,
		arg.Platform,
		arg.Category,
		arg.ProviderID,
		arg.ProviderServiceID,
		arg.IsActive,
	)
	var i PabloCatalog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VariantName,
		&i.SellPriceInr,
		&i.Platform,
		&i.Category,
		&i.IsActive,
		&i.ProviderID,
		&i.ProviderServiceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCatalogService = `-- name: DeleteCatalogService :exec
DELETE FROM pablo_catalog WHERE id = $1
`

func (q *Queries) DeleteCatalogService(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCatalogService, id)
	return err
}

const getActiveCatalogServices = `-- name: GetActiveCatalogServices :many
SELECT id, name, variant_name, sell_price_inr, platform, category, is_active, provider_id, provider_service_id, created_at, updated_at FROM pablo_catalog WHERE is_active = true ORDER BY created_at DESC
`

func (q *Queries) GetActiveCatalogServices(ctx context.Context) ([]PabloCatalog, error) {
	rows, err := q.db.Query(ctx, getActiveCatalogServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PabloCatalog
	for rows.Next() {
		var i PabloCatalog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.VariantName,
			&i.SellPriceInr,
			&i.Platform,
			&i.Category,
			&i.IsActive,
			&i.ProviderID,
			&i.ProviderServiceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCatalogServices = `-- name: GetAllCatalogServices :many
SELECT id, name, variant_name, sell_price_inr, platform, category, is_active, provider_id, provider_service_id, created_at, updated_at FROM pablo_catalog ORDER BY created_at DESC
`

func (q *Queries) GetAllCatalogServices(ctx context.Context) ([]PabloCatalog, error) {
	rows, err := q.db.Query(ctx, getAllCatalogServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PabloCatalog
	for rows.Next() {
		var i PabloCatalog
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.VariantName,
			&i.SellPriceInr,
			&i.Platform,
			&i.Category,
			&i.IsActive,
			&i.ProviderID,
			&i.ProviderServiceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCatalogService = `-- name: GetCatalogService :one
SELECT id, name, variant_name, sell_price_inr, platform, category, is_active, provider_id, provider_service_id, created_at, updated_at FROM pablo_catalog WHERE id = $1
`

func (q *Queries) GetCatalogService(ctx context.Context, id int32) (PabloCatalog, error) {
	row := q.db.QueryRow(ctx, getCatalogService, id)
	var i PabloCatalog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VariantName,
		&i.SellPriceInr,
		&i.Platform,
		&i.Category,
		&i.IsActive,
		&i.ProviderID,
		&i.ProviderServiceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCatalogService = `-- name: UpdateCatalogService :one
UPDATE pablo_catalog 
SET 
    name = $2,
    variant_name = $3,
    sell_price_inr = $4,
    platform = $5,
    category = $6,
    provider_id = $7,
    provider_service_id = $8,
    is_active = $9
WHERE id = $1
RETURNING id, name, variant_name, sell_price_inr, platform, category, is_active, provider_id, provider_service_id, created_at, updated_at
`

type UpdateCatalogServiceParams struct {
	ID                int32          `json:"id"`
	Name              string         `json:"name"`
	VariantName       pgtype.Text    `json:"variant_name"`
	SellPriceInr      pgtype.Numeric `json:"sell_price_inr"`
	Platform          pgtype.Text    `json:"platform"`
	Category          pgtype.Text    `json:"category"`
	ProviderID        pgtype.Text    `json:"provider_id"`
	ProviderServiceID pgtype.Text    `json:"provider_service_id"`
	IsActive          pgtype.Bool    `json:"is_active"`
}

func (q *Queries) UpdateCatalogService(ctx context.Context, arg UpdateCatalogServiceParams) (PabloCatalog, error) {
	row := q.db.QueryRow(ctx, updateCatalogService,
		arg.ID,
		arg.Name,
		arg.VariantName,
		arg.SellPriceInr,
		arg.Platform,
		arg.Category,
		arg.ProviderID,
		arg.ProviderServiceID,
		arg.IsActive,
	)
	var i PabloCatalog
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.VariantName,
		&i.SellPriceInr,
		&i.Platform,
		&i.Category,
		&i.IsActive,
		&i.ProviderID,
		&i.ProviderServiceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
