// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                int32       `json:"id"`
	UserID            int32       `json:"user_id"`
	Type              string      `json:"type"`
	Provider          string      `json:"provider"`
	ProviderAccountID string      `json:"provider_account_id"`
	RefreshToken      pgtype.Text `json:"refresh_token"`
	AccessToken       pgtype.Text `json:"access_token"`
	ExpiresAt         pgtype.Int4 `json:"expires_at"`
	TokenType         pgtype.Text `json:"token_type"`
	Scope             pgtype.Text `json:"scope"`
	IDToken           pgtype.Text `json:"id_token"`
	SessionState      pgtype.Text `json:"session_state"`
}

type GlobalSetting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID               int32              `json:"id"`
	UserID           int32              `json:"user_id"`
	ServiceID        string             `json:"service_id"`
	Quantity         int32              `json:"quantity"`
	AmountCents      int32              `json:"amount_cents"`
	Status           string             `json:"status"`
	ProviderResp     []byte             `json:"provider_resp"`
	ProviderOrderID  pgtype.Text        `json:"provider_order_id"`
	RefundedAmount   pgtype.Int4        `json:"refunded_amount"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Remains          pgtype.Int4        `json:"remains"`
	StartCount       pgtype.Int4        `json:"start_count"`
	Link             pgtype.Text        `json:"link"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	RefillsRemaining pgtype.Int4        `json:"refills_remaining"`
}

type OrderRequest struct {
	ID               int32              `json:"id"`
	OrderID          int32              `json:"order_id"`
	UserID           int32              `json:"user_id"`
	RequestType      string             `json:"request_type"`
	Status           pgtype.Text        `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ProviderResponse pgtype.Text        `json:"provider_response"`
}

type ServiceOverride struct {
	ID                 int32              `json:"id"`
	SourceServiceID    string             `json:"source_service_id"`
	DisplayName        pgtype.Text        `json:"display_name"`
	DisplayDescription pgtype.Text        `json:"display_description"`
	RateMultiplier     pgtype.Float8      `json:"rate_multiplier"`
	IsHidden           pgtype.Bool        `json:"is_hidden"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Category           pgtype.Text        `json:"category"`
	Tags               []string           `json:"tags"`
	ProviderCategory   pgtype.Text        `json:"provider_category"`
	PurchaseCount      pgtype.Int4        `json:"purchase_count"`
	DisplayID          pgtype.Text        `json:"display_id"`
	Refill             pgtype.Bool        `json:"refill"`
	Cancel             pgtype.Bool        `json:"cancel"`
	Dripfeed           pgtype.Bool        `json:"dripfeed"`
	ServiceType        pgtype.Text        `json:"service_type"`
	Targeting          pgtype.Text        `json:"targeting"`
	Quality            pgtype.Text        `json:"quality"`
	Stability          pgtype.Text        `json:"stability"`
	RefillLimit        pgtype.Int4        `json:"refill_limit"`
}

type Session struct {
	ID           int32              `json:"id"`
	SessionToken string             `json:"session_token"`
	UserID       int32              `json:"user_id"`
	Expires      pgtype.Timestamptz `json:"expires"`
}

type Transaction struct {
	ID          int32              `json:"id"`
	UserID      pgtype.Int4        `json:"user_id"`
	Amount      pgtype.Numeric     `json:"amount"`
	Type        string             `json:"type"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type UpiNotification struct {
	ID               int32              `json:"id"`
	Amount           pgtype.Numeric     `json:"amount"`
	Utr              pgtype.Text        `json:"utr"`
	SenderUpi        pgtype.Text        `json:"sender_upi"`
	RawText          pgtype.Text        `json:"raw_text"`
	MatchedRequestID pgtype.Int4        `json:"matched_request_id"`
	Status           pgtype.Text        `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            int32              `json:"id"`
	Name          pgtype.Text        `json:"name"`
	Email         pgtype.Text        `json:"email"`
	EmailVerified pgtype.Timestamptz `json:"email_verified"`
	Image         pgtype.Text        `json:"image"`
	Role          string             `json:"role"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Username      pgtype.Text        `json:"username"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	Mobile        pgtype.Text        `json:"mobile"`
	GoogleID      pgtype.Text        `json:"google_id"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	ApiKey        pgtype.Text        `json:"api_key"`
	ApiKeyEnabled pgtype.Bool        `json:"api_key_enabled"`
	Currency      pgtype.Text        `json:"currency"`
}

type VerificationToken struct {
	Identifier string             `json:"identifier"`
	Token      string             `json:"token"`
	Expires    pgtype.Timestamptz `json:"expires"`
}

type Wallet struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	Balance   int32              `json:"balance"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WalletRequest struct {
	ID            int32              `json:"id"`
	UserID        pgtype.Int4        `json:"user_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	Method        string             `json:"method"`
	TransactionID pgtype.Text        `json:"transaction_id"`
	Status        pgtype.Text        `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	UniqueAmount  pgtype.Numeric     `json:"unique_amount"`
}
