// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_requests.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderRequest = `-- name: CreateOrderRequest :one
INSERT INTO order_requests (order_id, user_id, request_type, provider_response, status)
VALUES ($1, $2, $3, $4, 'pending')
RETURNING id, order_id, user_id, request_type, status, created_at, updated_at
`

type CreateOrderRequestParams struct {
	OrderID          int32       `json:"order_id"`
	UserID           int32       `json:"user_id"`
	RequestType      string      `json:"request_type"`
	ProviderResponse pgtype.Text `json:"provider_response"`
}

type CreateOrderRequestRow struct {
	ID          int32              `json:"id"`
	OrderID     int32              `json:"order_id"`
	UserID      int32              `json:"user_id"`
	RequestType string             `json:"request_type"`
	Status      pgtype.Text        `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrderRequest(ctx context.Context, arg CreateOrderRequestParams) (CreateOrderRequestRow, error) {
	row := q.db.QueryRow(ctx, createOrderRequest,
		arg.OrderID,
		arg.UserID,
		arg.RequestType,
		arg.ProviderResponse,
	)
	var i CreateOrderRequestRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.RequestType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementOrderRefills = `-- name: DecrementOrderRefills :exec
UPDATE orders
SET refills_remaining = refills_remaining - 1
WHERE id = $1 AND refills_remaining > 0
`

func (q *Queries) DecrementOrderRefills(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, decrementOrderRefills, id)
	return err
}

const getPendingOrderRequestsByOrder = `-- name: GetPendingOrderRequestsByOrder :many
SELECT id, order_id, user_id, request_type, status, created_at, updated_at, provider_response FROM order_requests
WHERE order_id = $1 AND status = 'pending'
`

func (q *Queries) GetPendingOrderRequestsByOrder(ctx context.Context, orderID int32) ([]OrderRequest, error) {
	rows, err := q.db.Query(ctx, getPendingOrderRequestsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderRequest
	for rows.Next() {
		var i OrderRequest
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.RequestType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderResponse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOrderRequests = `-- name: ListPendingOrderRequests :many
SELECT req.id, req.order_id, req.user_id, req.request_type, req.status, req.created_at, req.updated_at,
       req.provider_response,
       o.service_id, o.quantity, o.provider_order_id, o.status as order_status,
       u.email, u.username
FROM order_requests req
JOIN orders o ON req.order_id = o.id
JOIN users u ON req.user_id = u.id
WHERE req.status = 'pending'
ORDER BY req.created_at DESC
`

type ListPendingOrderRequestsRow struct {
	ID               int32              `json:"id"`
	OrderID          int32              `json:"order_id"`
	UserID           int32              `json:"user_id"`
	RequestType      string             `json:"request_type"`
	Status           pgtype.Text        `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ProviderResponse pgtype.Text        `json:"provider_response"`
	ServiceID        string             `json:"service_id"`
	Quantity         int32              `json:"quantity"`
	ProviderOrderID  pgtype.Text        `json:"provider_order_id"`
	OrderStatus      string             `json:"order_status"`
	Email            pgtype.Text        `json:"email"`
	Username         pgtype.Text        `json:"username"`
}

func (q *Queries) ListPendingOrderRequests(ctx context.Context) ([]ListPendingOrderRequestsRow, error) {
	rows, err := q.db.Query(ctx, listPendingOrderRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingOrderRequestsRow
	for rows.Next() {
		var i ListPendingOrderRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.RequestType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderResponse,
			&i.ServiceID,
			&i.Quantity,
			&i.ProviderOrderID,
			&i.OrderStatus,
			&i.Email,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderRequestStatus = `-- name: UpdateOrderRequestStatus :exec
UPDATE order_requests
SET status = $2
WHERE id = $1
`

type UpdateOrderRequestStatusParams struct {
	ID     int32       `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateOrderRequestStatus(ctx context.Context, arg UpdateOrderRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderRequestStatus, arg.ID, arg.Status)
	return err
}
