// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOrder = `-- name: CancelOrder :exec
UPDATE orders SET status='canceled' WHERE id=$1
`

func (q *Queries) CancelOrder(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, cancelOrder, id)
	return err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const getAdminOrders = `-- name: GetAdminOrders :many
SELECT 
	o.id, 
	o.service_id, 
	o.amount_cents, 
	o.quantity, 
	o.status, 
	o.created_at, 
	COALESCE(o.provider_order_id, '')::text as provider_order_id,
	COALESCE(so.display_id, '')::text as display_id,
	COALESCE(so.display_name, '')::text as display_name,
	COALESCE(o.remains, 0)::int as remains,
	COALESCE(o.start_count, 0)::int as start_count,
	COALESCE(o.link, '')::text as link,
	u.email,
	COALESCE(o.refunded_amount, 0)::int as refunded_amount
FROM orders o
LEFT JOIN service_overrides so ON (o.service_id = so.source_service_id OR split_part(o.service_id, ':', 2) = so.source_service_id)
JOIN users u ON o.user_id = u.id
WHERE ($1::text IS NULL OR o.status = $1)
AND ($2::int IS NULL OR o.user_id = $2)
ORDER BY o.created_at DESC
`

type GetAdminOrdersParams struct {
	StatusFilter pgtype.Text `json:"status_filter"`
	UserID       pgtype.Int4 `json:"user_id"`
}

type GetAdminOrdersRow struct {
	ID              int32              `json:"id"`
	ServiceID       string             `json:"service_id"`
	AmountCents     int32              `json:"amount_cents"`
	Quantity        int32              `json:"quantity"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ProviderOrderID string             `json:"provider_order_id"`
	DisplayID       string             `json:"display_id"`
	DisplayName     string             `json:"display_name"`
	Remains         int32              `json:"remains"`
	StartCount      int32              `json:"start_count"`
	Link            string             `json:"link"`
	Email           pgtype.Text        `json:"email"`
	RefundedAmount  int32              `json:"refunded_amount"`
}

func (q *Queries) GetAdminOrders(ctx context.Context, arg GetAdminOrdersParams) ([]GetAdminOrdersRow, error) {
	rows, err := q.db.Query(ctx, getAdminOrders, arg.StatusFilter, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminOrdersRow
	for rows.Next() {
		var i GetAdminOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.AmountCents,
			&i.Quantity,
			&i.Status,
			&i.CreatedAt,
			&i.ProviderOrderID,
			&i.DisplayID,
			&i.DisplayName,
			&i.Remains,
			&i.StartCount,
			&i.Link,
			&i.Email,
			&i.RefundedAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderForCancel = `-- name: GetOrderForCancel :one
SELECT status, amount_cents, COALESCE(provider_order_id, '')::text as provider_order_id 
FROM orders 
WHERE id=$1 AND user_id=$2 
FOR UPDATE
`

type GetOrderForCancelParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetOrderForCancelRow struct {
	Status          string `json:"status"`
	AmountCents     int32  `json:"amount_cents"`
	ProviderOrderID string `json:"provider_order_id"`
}

func (q *Queries) GetOrderForCancel(ctx context.Context, arg GetOrderForCancelParams) (GetOrderForCancelRow, error) {
	row := q.db.QueryRow(ctx, getOrderForCancel, arg.ID, arg.UserID)
	var i GetOrderForCancelRow
	err := row.Scan(&i.Status, &i.AmountCents, &i.ProviderOrderID)
	return i, err
}

const getOrderForRefundAdmin = `-- name: GetOrderForRefundAdmin :one
SELECT status, amount_cents, COALESCE(refunded_amount, 0)::int as refunded_amount, user_id 
FROM orders WHERE id = $1 FOR UPDATE
`

type GetOrderForRefundAdminRow struct {
	Status         string `json:"status"`
	AmountCents    int32  `json:"amount_cents"`
	RefundedAmount int32  `json:"refunded_amount"`
	UserID         int32  `json:"user_id"`
}

func (q *Queries) GetOrderForRefundAdmin(ctx context.Context, id int32) (GetOrderForRefundAdminRow, error) {
	row := q.db.QueryRow(ctx, getOrderForRefundAdmin, id)
	var i GetOrderForRefundAdminRow
	err := row.Scan(
		&i.Status,
		&i.AmountCents,
		&i.RefundedAmount,
		&i.UserID,
	)
	return i, err
}

const getOrders = `-- name: GetOrders :many
SELECT 
	o.id, 
	o.service_id, 
	o.amount_cents, 
	o.quantity, 
	o.status, 
	o.created_at, 
	o.provider_order_id,
	COALESCE(so.display_id, '')::text as display_id,
	COALESCE(so.display_name, '')::text as display_name,
	COALESCE(o.remains, 0)::int as remains,
	COALESCE(o.start_count, 0)::int as start_count,
	COALESCE(o.link, '')::text as link,
	(SELECT COALESCE(balance, 0)::int FROM wallets WHERE user_id = o.user_id) as user_balance,
	COALESCE(so.service_type, '')::text as service_type,
	COALESCE(so.category, '')::text as category
FROM orders o
LEFT JOIN service_overrides so ON (
	o.service_id = so.source_service_id 
	OR split_part(o.service_id, ':', 2) = so.source_service_id
	OR o.service_id = so.source_service_id || ':' || split_part(o.service_id, ':', 2)
	OR split_part(o.service_id, ':', 2) = split_part(so.source_service_id, ':', 2)
)
WHERE o.user_id = $1
AND ($2::text IS NULL OR 
     ($2 = 'active' AND o.status IN ('pending', 'processing', 'submitted', 'active', 'in_progress')) OR
     ($2 != 'active' AND o.status = $2)
    )
ORDER BY o.created_at DESC
`

type GetOrdersParams struct {
	UserID       int32       `json:"user_id"`
	StatusFilter pgtype.Text `json:"status_filter"`
}

type GetOrdersRow struct {
	ID              int32              `json:"id"`
	ServiceID       string             `json:"service_id"`
	AmountCents     int32              `json:"amount_cents"`
	Quantity        int32              `json:"quantity"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ProviderOrderID pgtype.Text        `json:"provider_order_id"`
	DisplayID       string             `json:"display_id"`
	DisplayName     string             `json:"display_name"`
	Remains         int32              `json:"remains"`
	StartCount      int32              `json:"start_count"`
	Link            string             `json:"link"`
	UserBalance     int32              `json:"user_balance"`
	ServiceType     string             `json:"service_type"`
	Category        string             `json:"category"`
}

func (q *Queries) GetOrders(ctx context.Context, arg GetOrdersParams) ([]GetOrdersRow, error) {
	rows, err := q.db.Query(ctx, getOrders, arg.UserID, arg.StatusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersRow
	for rows.Next() {
		var i GetOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.AmountCents,
			&i.Quantity,
			&i.Status,
			&i.CreatedAt,
			&i.ProviderOrderID,
			&i.DisplayID,
			&i.DisplayName,
			&i.Remains,
			&i.StartCount,
			&i.Link,
			&i.UserBalance,
			&i.ServiceType,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSingleOrder = `-- name: GetSingleOrder :one
SELECT 
	o.id, 
	o.service_id, 
	o.amount_cents, 
	o.quantity, 
	o.status, 
	o.created_at, 
    o.updated_at,
	COALESCE(so.display_id, '')::text as display_id,
	COALESCE(so.display_name, '')::text as display_name,
	COALESCE(o.remains, 0)::int as remains,
	COALESCE(o.start_count, 0)::int as start_count,
	COALESCE(o.link, '')::text as link,
	COALESCE(so.service_type, '')::text as service_type,
	COALESCE(so.category, '')::text as category
FROM orders o
LEFT JOIN service_overrides so ON (
	o.service_id = so.source_service_id 
	OR split_part(o.service_id, ':', 2) = so.source_service_id
	OR o.service_id = so.source_service_id || ':' || split_part(o.service_id, ':', 2)
	OR split_part(o.service_id, ':', 2) = split_part(so.source_service_id, ':', 2)
)
WHERE o.id = $1 AND o.user_id = $2
`

type GetSingleOrderParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

type GetSingleOrderRow struct {
	ID          int32              `json:"id"`
	ServiceID   string             `json:"service_id"`
	AmountCents int32              `json:"amount_cents"`
	Quantity    int32              `json:"quantity"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DisplayID   string             `json:"display_id"`
	DisplayName string             `json:"display_name"`
	Remains     int32              `json:"remains"`
	StartCount  int32              `json:"start_count"`
	Link        string             `json:"link"`
	ServiceType string             `json:"service_type"`
	Category    string             `json:"category"`
}

func (q *Queries) GetSingleOrder(ctx context.Context, arg GetSingleOrderParams) (GetSingleOrderRow, error) {
	row := q.db.QueryRow(ctx, getSingleOrder, arg.ID, arg.UserID)
	var i GetSingleOrderRow
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.AmountCents,
		&i.Quantity,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayID,
		&i.DisplayName,
		&i.Remains,
		&i.StartCount,
		&i.Link,
		&i.ServiceType,
		&i.Category,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (user_id, service_id, amount_cents, quantity, link, status, provider_order_id, provider_resp)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type InsertOrderParams struct {
	UserID          int32       `json:"user_id"`
	ServiceID       string      `json:"service_id"`
	AmountCents     int32       `json:"amount_cents"`
	Quantity        int32       `json:"quantity"`
	Link            pgtype.Text `json:"link"`
	Status          string      `json:"status"`
	ProviderOrderID pgtype.Text `json:"provider_order_id"`
	ProviderResp    []byte      `json:"provider_resp"`
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.UserID,
		arg.ServiceID,
		arg.AmountCents,
		arg.Quantity,
		arg.Link,
		arg.Status,
		arg.ProviderOrderID,
		arg.ProviderResp,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateOrderProvider = `-- name: UpdateOrderProvider :exec
UPDATE orders SET provider_resp = $1, provider_order_id = $2, status = $3 WHERE id = $4
`

type UpdateOrderProviderParams struct {
	ProviderResp    []byte      `json:"provider_resp"`
	ProviderOrderID pgtype.Text `json:"provider_order_id"`
	Status          string      `json:"status"`
	ID              int32       `json:"id"`
}

func (q *Queries) UpdateOrderProvider(ctx context.Context, arg UpdateOrderProviderParams) error {
	_, err := q.db.Exec(ctx, updateOrderProvider,
		arg.ProviderResp,
		arg.ProviderOrderID,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateOrderRefundAdmin = `-- name: UpdateOrderRefundAdmin :one
UPDATE orders SET status = $1, refunded_amount = $2 WHERE id = $3 RETURNING COALESCE(provider_order_id, '')::text
`

type UpdateOrderRefundAdminParams struct {
	Status         string      `json:"status"`
	RefundedAmount pgtype.Int4 `json:"refunded_amount"`
	ID             int32       `json:"id"`
}

func (q *Queries) UpdateOrderRefundAdmin(ctx context.Context, arg UpdateOrderRefundAdminParams) (string, error) {
	row := q.db.QueryRow(ctx, updateOrderRefundAdmin, arg.Status, arg.RefundedAmount, arg.ID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}
