// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
)

const deleteSmmProvider = `-- name: DeleteSmmProvider :exec
DELETE FROM smm_providers WHERE id = $1
`

func (q *Queries) DeleteSmmProvider(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSmmProvider, id)
	return err
}

const getActiveSmmProviders = `-- name: GetActiveSmmProviders :many
SELECT id, key, name, api_url, api_key, currency, is_active, created_at, updated_at
FROM smm_providers
WHERE is_active = TRUE
ORDER BY id ASC
`

func (q *Queries) GetActiveSmmProviders(ctx context.Context) ([]SmmProvider, error) {
	rows, err := q.db.Query(ctx, getActiveSmmProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmmProvider
	for rows.Next() {
		var i SmmProvider
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.ApiUrl,
			&i.ApiKey,
			&i.Currency,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSmmProviderByKey = `-- name: GetSmmProviderByKey :one
SELECT id, key, name, api_url, api_key, currency, is_active, created_at, updated_at
FROM smm_providers
WHERE key = $1
`

func (q *Queries) GetSmmProviderByKey(ctx context.Context, key string) (SmmProvider, error) {
	row := q.db.QueryRow(ctx, getSmmProviderByKey, key)
	var i SmmProvider
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.ApiUrl,
		&i.ApiKey,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSmmProvidersAdmin = `-- name: ListSmmProvidersAdmin :many
SELECT id, key, name, api_url, api_key, currency, is_active, created_at, updated_at
FROM smm_providers
ORDER BY id ASC
`

func (q *Queries) ListSmmProvidersAdmin(ctx context.Context) ([]SmmProvider, error) {
	rows, err := q.db.Query(ctx, listSmmProvidersAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SmmProvider
	for rows.Next() {
		var i SmmProvider
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.ApiUrl,
			&i.ApiKey,
			&i.Currency,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSmmProvider = `-- name: UpsertSmmProvider :one
INSERT INTO smm_providers (key, name, api_url, api_key, currency, is_active, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, CURRENT_TIMESTAMP)
ON CONFLICT (key)
DO UPDATE SET
    name = EXCLUDED.name,
    api_url = EXCLUDED.api_url,
    api_key = EXCLUDED.api_key,
    currency = EXCLUDED.currency,
    is_active = EXCLUDED.is_active,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, key, name, api_url, api_key, currency, is_active, created_at, updated_at
`

type UpsertSmmProviderParams struct {
	Key      string `json:"key"`
	Name     string `json:"name"`
	ApiUrl   string `json:"api_url"`
	ApiKey   string `json:"api_key"`
	Currency string `json:"currency"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) UpsertSmmProvider(ctx context.Context, arg UpsertSmmProviderParams) (SmmProvider, error) {
	row := q.db.QueryRow(ctx, upsertSmmProvider,
		arg.Key,
		arg.Name,
		arg.ApiUrl,
		arg.ApiKey,
		arg.Currency,
		arg.IsActive,
	)
	var i SmmProvider
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.ApiUrl,
		&i.ApiKey,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
