// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpsertServiceOverride = `-- name: BulkUpsertServiceOverride :exec
INSERT INTO service_overrides (
    source_service_id, display_name, display_description, rate_multiplier, is_hidden, 
    category, tags, provider_category, display_id, 
    refill, cancel, dripfeed, service_type,
    targeting, quality, stability, updated_at
)
VALUES ($1, 
    COALESCE($2, ''),
    COALESCE($3, ''),
    CASE WHEN $4 > 0 THEN $4 ELSE 1.0 END,
    COALESCE($5, false),
    COALESCE($6, ''),
    COALESCE($7, '{}'::text[]),
    COALESCE($8, ''),
    COALESCE($9, ''),
    COALESCE($10, false),
    COALESCE($11, false),
    COALESCE($12, false),
    COALESCE($13, ''),
    COALESCE($14, ''),
    COALESCE($15, ''),
    COALESCE($16, ''),
    CURRENT_TIMESTAMP)
ON CONFLICT (source_service_id) 
DO UPDATE SET 
    display_name = COALESCE(EXCLUDED.display_name, service_overrides.display_name),
    display_description = COALESCE(EXCLUDED.display_description, service_overrides.display_description),
    rate_multiplier = CASE WHEN EXCLUDED.rate_multiplier > 0 THEN EXCLUDED.rate_multiplier ELSE service_overrides.rate_multiplier END,
    is_hidden = COALESCE(EXCLUDED.is_hidden, service_overrides.is_hidden),
    category = COALESCE(EXCLUDED.category, service_overrides.category),
    tags = COALESCE(EXCLUDED.tags, service_overrides.tags),
    provider_category = COALESCE(EXCLUDED.provider_category, service_overrides.provider_category),
    display_id = COALESCE(EXCLUDED.display_id, service_overrides.display_id),
    refill = COALESCE(EXCLUDED.refill, service_overrides.refill),
    cancel = COALESCE(EXCLUDED.cancel, service_overrides.cancel),
    dripfeed = COALESCE(EXCLUDED.dripfeed, service_overrides.dripfeed),
    service_type = COALESCE(EXCLUDED.service_type, service_overrides.service_type),
    targeting = COALESCE(EXCLUDED.targeting, service_overrides.targeting),
    quality = COALESCE(EXCLUDED.quality, service_overrides.quality),
    stability = COALESCE(EXCLUDED.stability, service_overrides.stability),
    updated_at = CURRENT_TIMESTAMP
`

type BulkUpsertServiceOverrideParams struct {
	SourceServiceID string      `json:"source_service_id"`
	Column2         interface{} `json:"column_2"`
	Column3         interface{} `json:"column_3"`
	Column4         interface{} `json:"column_4"`
	Column5         interface{} `json:"column_5"`
	Column6         interface{} `json:"column_6"`
	Column7         interface{} `json:"column_7"`
	Column8         interface{} `json:"column_8"`
	Column9         interface{} `json:"column_9"`
	Column10        interface{} `json:"column_10"`
	Column11        interface{} `json:"column_11"`
	Column12        interface{} `json:"column_12"`
	Column13        interface{} `json:"column_13"`
	Column14        interface{} `json:"column_14"`
	Column15        interface{} `json:"column_15"`
	Column16        interface{} `json:"column_16"`
}

func (q *Queries) BulkUpsertServiceOverride(ctx context.Context, arg BulkUpsertServiceOverrideParams) error {
	_, err := q.db.Exec(ctx, bulkUpsertServiceOverride,
		arg.SourceServiceID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
		arg.Column10,
		arg.Column11,
		arg.Column12,
		arg.Column13,
		arg.Column14,
		arg.Column15,
		arg.Column16,
	)
	return err
}

const getAllServiceOverrides = `-- name: GetAllServiceOverrides :many
SELECT source_service_id, display_name, display_description, rate_multiplier, is_hidden, category, tags, provider_category, purchase_count, display_id, refill, cancel, dripfeed, service_type, targeting, quality, stability FROM service_overrides
`

type GetAllServiceOverridesRow struct {
	SourceServiceID    string        `json:"source_service_id"`
	DisplayName        pgtype.Text   `json:"display_name"`
	DisplayDescription pgtype.Text   `json:"display_description"`
	RateMultiplier     pgtype.Float8 `json:"rate_multiplier"`
	IsHidden           pgtype.Bool   `json:"is_hidden"`
	Category           pgtype.Text   `json:"category"`
	Tags               []string      `json:"tags"`
	ProviderCategory   pgtype.Text   `json:"provider_category"`
	PurchaseCount      pgtype.Int4   `json:"purchase_count"`
	DisplayID          pgtype.Text   `json:"display_id"`
	Refill             pgtype.Bool   `json:"refill"`
	Cancel             pgtype.Bool   `json:"cancel"`
	Dripfeed           pgtype.Bool   `json:"dripfeed"`
	ServiceType        pgtype.Text   `json:"service_type"`
	Targeting          pgtype.Text   `json:"targeting"`
	Quality            pgtype.Text   `json:"quality"`
	Stability          pgtype.Text   `json:"stability"`
}

func (q *Queries) GetAllServiceOverrides(ctx context.Context) ([]GetAllServiceOverridesRow, error) {
	rows, err := q.db.Query(ctx, getAllServiceOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllServiceOverridesRow
	for rows.Next() {
		var i GetAllServiceOverridesRow
		if err := rows.Scan(
			&i.SourceServiceID,
			&i.DisplayName,
			&i.DisplayDescription,
			&i.RateMultiplier,
			&i.IsHidden,
			&i.Category,
			&i.Tags,
			&i.ProviderCategory,
			&i.PurchaseCount,
			&i.DisplayID,
			&i.Refill,
			&i.Cancel,
			&i.Dripfeed,
			&i.ServiceType,
			&i.Targeting,
			&i.Quality,
			&i.Stability,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileStats = `-- name: GetProfileStats :one
SELECT 
    COUNT(*) FILTER (WHERE status IN ('pending', 'processing', 'submitted', 'in_progress', 'active'))::int as active_count,
    COUNT(*) FILTER (WHERE status IN ('completed', 'partial'))::int as completed_count,
    COUNT(*) FILTER (WHERE status IN ('canceled', 'failed', 'refunded'))::int as failed_count
FROM orders 
WHERE user_id = $1
`

type GetProfileStatsRow struct {
	ActiveCount    int32 `json:"active_count"`
	CompletedCount int32 `json:"completed_count"`
	FailedCount    int32 `json:"failed_count"`
}

func (q *Queries) GetProfileStats(ctx context.Context, userID int32) (GetProfileStatsRow, error) {
	row := q.db.QueryRow(ctx, getProfileStats, userID)
	var i GetProfileStatsRow
	err := row.Scan(&i.ActiveCount, &i.CompletedCount, &i.FailedCount)
	return i, err
}

const getProfileTotalSpend = `-- name: GetProfileTotalSpend :one
SELECT COALESCE(SUM(
    CASE 
        WHEN status IN ('failed', 'canceled', 'refunded') THEN 0 
        ELSE amount_cents - COALESCE(refunded_amount, 0) 
    END
), 0)::int FROM orders WHERE user_id = $1
`

func (q *Queries) GetProfileTotalSpend(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getProfileTotalSpend, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const incrementServicePurchaseCount = `-- name: IncrementServicePurchaseCount :exec
INSERT INTO service_overrides (source_service_id, purchase_count, rate_multiplier, updated_at)
VALUES ($1, 1, 1.0, CURRENT_TIMESTAMP)
ON CONFLICT (source_service_id)
DO UPDATE SET purchase_count = service_overrides.purchase_count + 1, updated_at = CURRENT_TIMESTAMP
`

func (q *Queries) IncrementServicePurchaseCount(ctx context.Context, sourceServiceID string) error {
	_, err := q.db.Exec(ctx, incrementServicePurchaseCount, sourceServiceID)
	return err
}

const upsertServiceOverride = `-- name: UpsertServiceOverride :exec
INSERT INTO service_overrides (
    source_service_id, display_name, display_description, rate_multiplier, is_hidden, 
    category, tags, provider_category, display_id, refill, cancel, dripfeed, service_type,
    targeting, quality, stability, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, CURRENT_TIMESTAMP)
ON CONFLICT (source_service_id) 
DO UPDATE SET 
    display_name = EXCLUDED.display_name,
    display_description = EXCLUDED.display_description,
    rate_multiplier = EXCLUDED.rate_multiplier,
    is_hidden = EXCLUDED.is_hidden,
    category = EXCLUDED.category,
    tags = EXCLUDED.tags,
    provider_category = EXCLUDED.provider_category,
    display_id = EXCLUDED.display_id,
    refill = EXCLUDED.refill,
    cancel = EXCLUDED.cancel,
    dripfeed = EXCLUDED.dripfeed,
    service_type = EXCLUDED.service_type,
    targeting = EXCLUDED.targeting,
    quality = EXCLUDED.quality,
    stability = EXCLUDED.stability,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertServiceOverrideParams struct {
	SourceServiceID    string        `json:"source_service_id"`
	DisplayName        pgtype.Text   `json:"display_name"`
	DisplayDescription pgtype.Text   `json:"display_description"`
	RateMultiplier     pgtype.Float8 `json:"rate_multiplier"`
	IsHidden           pgtype.Bool   `json:"is_hidden"`
	Category           pgtype.Text   `json:"category"`
	Tags               []string      `json:"tags"`
	ProviderCategory   pgtype.Text   `json:"provider_category"`
	DisplayID          pgtype.Text   `json:"display_id"`
	Refill             pgtype.Bool   `json:"refill"`
	Cancel             pgtype.Bool   `json:"cancel"`
	Dripfeed           pgtype.Bool   `json:"dripfeed"`
	ServiceType        pgtype.Text   `json:"service_type"`
	Targeting          pgtype.Text   `json:"targeting"`
	Quality            pgtype.Text   `json:"quality"`
	Stability          pgtype.Text   `json:"stability"`
}

func (q *Queries) UpsertServiceOverride(ctx context.Context, arg UpsertServiceOverrideParams) error {
	_, err := q.db.Exec(ctx, upsertServiceOverride,
		arg.SourceServiceID,
		arg.DisplayName,
		arg.DisplayDescription,
		arg.RateMultiplier,
		arg.IsHidden,
		arg.Category,
		arg.Tags,
		arg.ProviderCategory,
		arg.DisplayID,
		arg.Refill,
		arg.Cancel,
		arg.Dripfeed,
		arg.ServiceType,
		arg.Targeting,
		arg.Quality,
		arg.Stability,
	)
	return err
}
