// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: syncer.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrderForSyncUpdate = `-- name: GetOrderForSyncUpdate :one
SELECT amount_cents, user_id, quantity, status FROM orders WHERE id = $1
`

type GetOrderForSyncUpdateRow struct {
	AmountCents int32  `json:"amount_cents"`
	UserID      int32  `json:"user_id"`
	Quantity    int32  `json:"quantity"`
	Status      string `json:"status"`
}

func (q *Queries) GetOrderForSyncUpdate(ctx context.Context, id int32) (GetOrderForSyncUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOrderForSyncUpdate, id)
	var i GetOrderForSyncUpdateRow
	err := row.Scan(
		&i.AmountCents,
		&i.UserID,
		&i.Quantity,
		&i.Status,
	)
	return i, err
}

const getOrdersForSync = `-- name: GetOrdersForSync :many
SELECT id, provider_order_id, status, COALESCE(provider_key, '')::text as provider_key 
FROM orders 
WHERE status IN ('pending', 'processing', 'submitted', 'in_progress', 'active', 'canceled', 'failed', 'completed', 'refunded') 
AND provider_order_id IS NOT NULL 
AND provider_order_id != ''
AND created_at > NOW() - INTERVAL '7 days'
LIMIT 100
`

type GetOrdersForSyncRow struct {
	ID              int32       `json:"id"`
	ProviderOrderID pgtype.Text `json:"provider_order_id"`
	Status          string      `json:"status"`
	ProviderKey     string      `json:"provider_key"`
}

func (q *Queries) GetOrdersForSync(ctx context.Context) ([]GetOrdersForSyncRow, error) {
	rows, err := q.db.Query(ctx, getOrdersForSync)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersForSyncRow
	for rows.Next() {
		var i GetOrdersForSyncRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderOrderID,
			&i.Status,
			&i.ProviderKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderSyncNoRefund = `-- name: UpdateOrderSyncNoRefund :exec
UPDATE orders 
SET status = $1, remains = $2, start_count = $3 
WHERE id = $4
`

type UpdateOrderSyncNoRefundParams struct {
	Status     string      `json:"status"`
	Remains    pgtype.Int4 `json:"remains"`
	StartCount pgtype.Int4 `json:"start_count"`
	ID         int32       `json:"id"`
}

func (q *Queries) UpdateOrderSyncNoRefund(ctx context.Context, arg UpdateOrderSyncNoRefundParams) error {
	_, err := q.db.Exec(ctx, updateOrderSyncNoRefund,
		arg.Status,
		arg.Remains,
		arg.StartCount,
		arg.ID,
	)
	return err
}

const updateOrderSyncWithRefund = `-- name: UpdateOrderSyncWithRefund :exec
UPDATE orders 
SET status = $1, remains = $2, start_count = $3, refunded_amount = COALESCE(refunded_amount, 0) + $4
WHERE id = $5
`

type UpdateOrderSyncWithRefundParams struct {
	Status         string      `json:"status"`
	Remains        pgtype.Int4 `json:"remains"`
	StartCount     pgtype.Int4 `json:"start_count"`
	RefundedAmount pgtype.Int4 `json:"refunded_amount"`
	ID             int32       `json:"id"`
}

func (q *Queries) UpdateOrderSyncWithRefund(ctx context.Context, arg UpdateOrderSyncWithRefundParams) error {
	_, err := q.db.Exec(ctx, updateOrderSyncWithRefund,
		arg.Status,
		arg.Remains,
		arg.StartCount,
		arg.RefundedAmount,
		arg.ID,
	)
	return err
}
