// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveCryptomusWalletRequest = `-- name: ApproveCryptomusWalletRequest :exec
UPDATE wallet_requests SET status='approved', updated_at=NOW() WHERE id=$1
`

func (q *Queries) ApproveCryptomusWalletRequest(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, approveCryptomusWalletRequest, id)
	return err
}

const checkPendingRequestCount = `-- name: CheckPendingRequestCount :one
SELECT COUNT(*) FROM wallet_requests
WHERE user_id = $1 AND status = 'pending'
`

func (q *Queries) CheckPendingRequestCount(ctx context.Context, userID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, checkPendingRequestCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkTransactionIDExists = `-- name: CheckTransactionIDExists :one
SELECT 1 FROM wallet_requests WHERE transaction_id=$1
`

func (q *Queries) CheckTransactionIDExists(ctx context.Context, transactionID pgtype.Text) (int32, error) {
	row := q.db.QueryRow(ctx, checkTransactionIDExists, transactionID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const checkUPINotificationExists = `-- name: CheckUPINotificationExists :one
SELECT id FROM upi_notifications WHERE utr = $1
`

func (q *Queries) CheckUPINotificationExists(ctx context.Context, utr pgtype.Text) (int32, error) {
	row := q.db.QueryRow(ctx, checkUPINotificationExists, utr)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const checkUniqueAmount = `-- name: CheckUniqueAmount :one
SELECT COUNT(*) FROM wallet_requests
WHERE unique_amount = $1
AND status = 'pending'
AND created_at > NOW() - INTERVAL '30 minutes'
`

func (q *Queries) CheckUniqueAmount(ctx context.Context, uniqueAmount pgtype.Numeric) (int64, error) {
	row := q.db.QueryRow(ctx, checkUniqueAmount, uniqueAmount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWalletTransactions = `-- name: CountWalletTransactions :one
SELECT COUNT(*) FROM transactions WHERE user_id = $1
`

func (q *Queries) CountWalletTransactions(ctx context.Context, userID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countWalletTransactions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCryptomusWalletRequest = `-- name: CreateCryptomusWalletRequest :one
INSERT INTO wallet_requests (user_id, amount, method, status)
VALUES ($1, $2, 'cryptomus', 'pending')
RETURNING id
`

type CreateCryptomusWalletRequestParams struct {
	UserID pgtype.Int4    `json:"user_id"`
	Amount pgtype.Numeric `json:"amount"`
}

func (q *Queries) CreateCryptomusWalletRequest(ctx context.Context, arg CreateCryptomusWalletRequestParams) (int32, error) {
	row := q.db.QueryRow(ctx, createCryptomusWalletRequest, arg.UserID, arg.Amount)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const creditWallet = `-- name: CreditWallet :exec
UPDATE wallets SET balance = balance + $1 WHERE user_id = $2
`

type CreditWalletParams struct {
	Balance int32 `json:"balance"`
	UserID  int32 `json:"user_id"`
}

func (q *Queries) CreditWallet(ctx context.Context, arg CreditWalletParams) error {
	_, err := q.db.Exec(ctx, creditWallet, arg.Balance, arg.UserID)
	return err
}

const debitWallet = `-- name: DebitWallet :exec
UPDATE wallets SET balance = balance - $1 WHERE user_id = $2
`

type DebitWalletParams struct {
	Balance int32 `json:"balance"`
	UserID  int32 `json:"user_id"`
}

func (q *Queries) DebitWallet(ctx context.Context, arg DebitWalletParams) error {
	_, err := q.db.Exec(ctx, debitWallet, arg.Balance, arg.UserID)
	return err
}

const findMatchingWalletRequest = `-- name: FindMatchingWalletRequest :one
SELECT id, user_id, amount FROM wallet_requests
WHERE status = 'pending'
AND method = 'UPI'
AND unique_amount IS NOT NULL
AND ABS(unique_amount - $1) < 0.005
AND created_at > NOW() - INTERVAL '30 minutes'
ORDER BY created_at DESC
LIMIT 1
`

type FindMatchingWalletRequestRow struct {
	ID     int32          `json:"id"`
	UserID pgtype.Int4    `json:"user_id"`
	Amount pgtype.Numeric `json:"amount"`
}

func (q *Queries) FindMatchingWalletRequest(ctx context.Context, uniqueAmount pgtype.Numeric) (FindMatchingWalletRequestRow, error) {
	row := q.db.QueryRow(ctx, findMatchingWalletRequest, uniqueAmount)
	var i FindMatchingWalletRequestRow
	err := row.Scan(&i.ID, &i.UserID, &i.Amount)
	return i, err
}

const findMatchingWalletRequestByUTR = `-- name: FindMatchingWalletRequestByUTR :one
SELECT id, user_id, amount FROM wallet_requests
WHERE status = 'pending'
AND method = 'UPI'
AND transaction_id = $1
ORDER BY created_at DESC
LIMIT 1
`

type FindMatchingWalletRequestByUTRRow struct {
	ID     int32          `json:"id"`
	UserID pgtype.Int4    `json:"user_id"`
	Amount pgtype.Numeric `json:"amount"`
}

func (q *Queries) FindMatchingWalletRequestByUTR(ctx context.Context, transactionID pgtype.Text) (FindMatchingWalletRequestByUTRRow, error) {
	row := q.db.QueryRow(ctx, findMatchingWalletRequestByUTR, transactionID)
	var i FindMatchingWalletRequestByUTRRow
	err := row.Scan(&i.ID, &i.UserID, &i.Amount)
	return i, err
}

const getAllMoneyTransactions = `-- name: GetAllMoneyTransactions :many
SELECT id, amount, type, description, created_at
FROM transactions
WHERE user_id = $1 AND type = 'credit'
ORDER BY created_at DESC
LIMIT 200
`

type GetAllMoneyTransactionsRow struct {
	ID          int32              `json:"id"`
	Amount      pgtype.Numeric     `json:"amount"`
	Type        string             `json:"type"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAllMoneyTransactions(ctx context.Context, userID pgtype.Int4) ([]GetAllMoneyTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getAllMoneyTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllMoneyTransactionsRow
	for rows.Next() {
		var i GetAllMoneyTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDepositStatus = `-- name: GetDepositStatus :one
SELECT status FROM wallet_requests WHERE id=$1 AND user_id=$2
`

type GetDepositStatusParams struct {
	ID     int32       `json:"id"`
	UserID pgtype.Int4 `json:"user_id"`
}

func (q *Queries) GetDepositStatus(ctx context.Context, arg GetDepositStatusParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getDepositStatus, arg.ID, arg.UserID)
	var status pgtype.Text
	err := row.Scan(&status)
	return status, err
}

const getRecentMoneyTransactions = `-- name: GetRecentMoneyTransactions :many
SELECT id, amount, type, description, created_at
FROM transactions
WHERE user_id = $1 AND type = 'credit'
ORDER BY created_at DESC
LIMIT 3
`

type GetRecentMoneyTransactionsRow struct {
	ID          int32              `json:"id"`
	Amount      pgtype.Numeric     `json:"amount"`
	Type        string             `json:"type"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetRecentMoneyTransactions(ctx context.Context, userID pgtype.Int4) ([]GetRecentMoneyTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getRecentMoneyTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentMoneyTransactionsRow
	for rows.Next() {
		var i GetRecentMoneyTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnmatchedUPINotification = `-- name: GetUnmatchedUPINotification :one
SELECT id, amount, utr, sender_upi FROM upi_notifications
WHERE utr = $1 AND status = 'unmatched' LIMIT 1
`

type GetUnmatchedUPINotificationRow struct {
	ID        int32          `json:"id"`
	Amount    pgtype.Numeric `json:"amount"`
	Utr       pgtype.Text    `json:"utr"`
	SenderUpi pgtype.Text    `json:"sender_upi"`
}

func (q *Queries) GetUnmatchedUPINotification(ctx context.Context, utr pgtype.Text) (GetUnmatchedUPINotificationRow, error) {
	row := q.db.QueryRow(ctx, getUnmatchedUPINotification, utr)
	var i GetUnmatchedUPINotificationRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Utr,
		&i.SenderUpi,
	)
	return i, err
}

const getWalletBalance = `-- name: GetWalletBalance :one
SELECT balance FROM wallets WHERE user_id = $1
`

func (q *Queries) GetWalletBalance(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getWalletBalance, userID)
	var balance int32
	err := row.Scan(&balance)
	return balance, err
}

const getWalletRequestAmount = `-- name: GetWalletRequestAmount :one
SELECT amount FROM wallet_requests WHERE id=$1
`

func (q *Queries) GetWalletRequestAmount(ctx context.Context, id int32) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getWalletRequestAmount, id)
	var amount pgtype.Numeric
	err := row.Scan(&amount)
	return amount, err
}

const getWalletRequestForUpdateAdmin = `-- name: GetWalletRequestForUpdateAdmin :one
SELECT user_id, amount, status FROM wallet_requests WHERE id=$1 FOR UPDATE
`

type GetWalletRequestForUpdateAdminRow struct {
	UserID pgtype.Int4    `json:"user_id"`
	Amount pgtype.Numeric `json:"amount"`
	Status pgtype.Text    `json:"status"`
}

func (q *Queries) GetWalletRequestForUpdateAdmin(ctx context.Context, id int32) (GetWalletRequestForUpdateAdminRow, error) {
	row := q.db.QueryRow(ctx, getWalletRequestForUpdateAdmin, id)
	var i GetWalletRequestForUpdateAdminRow
	err := row.Scan(&i.UserID, &i.Amount, &i.Status)
	return i, err
}

const getWalletRequestStatus = `-- name: GetWalletRequestStatus :one
SELECT status FROM wallet_requests WHERE id=$1
`

func (q *Queries) GetWalletRequestStatus(ctx context.Context, id int32) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getWalletRequestStatus, id)
	var status pgtype.Text
	err := row.Scan(&status)
	return status, err
}

const getWalletRequestStatusForUpdate = `-- name: GetWalletRequestStatusForUpdate :one
SELECT status FROM wallet_requests WHERE id=$1 FOR UPDATE
`

func (q *Queries) GetWalletRequestStatusForUpdate(ctx context.Context, id int32) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getWalletRequestStatusForUpdate, id)
	var status pgtype.Text
	err := row.Scan(&status)
	return status, err
}

const getWalletTransactions = `-- name: GetWalletTransactions :many
SELECT id, user_id, amount, type, description, created_at FROM transactions WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetWalletTransactionsParams struct {
	UserID pgtype.Int4 `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetWalletTransactions(ctx context.Context, arg GetWalletTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getWalletTransactions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTransaction = `-- name: InsertTransaction :exec
INSERT INTO transactions (user_id, amount, type, description)
VALUES ($1, $2, $3, $4)
`

type InsertTransactionParams struct {
	UserID      pgtype.Int4    `json:"user_id"`
	Amount      pgtype.Numeric `json:"amount"`
	Type        string         `json:"type"`
	Description pgtype.Text    `json:"description"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) error {
	_, err := q.db.Exec(ctx, insertTransaction,
		arg.UserID,
		arg.Amount,
		arg.Type,
		arg.Description,
	)
	return err
}

const insertUPINotificationMatched = `-- name: InsertUPINotificationMatched :exec
INSERT INTO upi_notifications (amount, utr, sender_upi, raw_text, matched_request_id, status)
VALUES ($1, $2, $3, $4, $5, 'matched')
`

type InsertUPINotificationMatchedParams struct {
	Amount           pgtype.Numeric `json:"amount"`
	Utr              pgtype.Text    `json:"utr"`
	SenderUpi        pgtype.Text    `json:"sender_upi"`
	RawText          pgtype.Text    `json:"raw_text"`
	MatchedRequestID pgtype.Int4    `json:"matched_request_id"`
}

func (q *Queries) InsertUPINotificationMatched(ctx context.Context, arg InsertUPINotificationMatchedParams) error {
	_, err := q.db.Exec(ctx, insertUPINotificationMatched,
		arg.Amount,
		arg.Utr,
		arg.SenderUpi,
		arg.RawText,
		arg.MatchedRequestID,
	)
	return err
}

const insertUPINotificationUnmatched = `-- name: InsertUPINotificationUnmatched :exec
INSERT INTO upi_notifications (amount, utr, sender_upi, raw_text, status)
VALUES ($1, $2, $3, $4, 'unmatched')
`

type InsertUPINotificationUnmatchedParams struct {
	Amount    pgtype.Numeric `json:"amount"`
	Utr       pgtype.Text    `json:"utr"`
	SenderUpi pgtype.Text    `json:"sender_upi"`
	RawText   pgtype.Text    `json:"raw_text"`
}

func (q *Queries) InsertUPINotificationUnmatched(ctx context.Context, arg InsertUPINotificationUnmatchedParams) error {
	_, err := q.db.Exec(ctx, insertUPINotificationUnmatched,
		arg.Amount,
		arg.Utr,
		arg.SenderUpi,
		arg.RawText,
	)
	return err
}

const insertWalletRequest = `-- name: InsertWalletRequest :one
INSERT INTO wallet_requests (user_id, amount, unique_amount, method, transaction_id, status)
VALUES ($1, $2, $3, $4, $5, 'pending')
RETURNING id
`

type InsertWalletRequestParams struct {
	UserID        pgtype.Int4    `json:"user_id"`
	Amount        pgtype.Numeric `json:"amount"`
	UniqueAmount  pgtype.Numeric `json:"unique_amount"`
	Method        string         `json:"method"`
	TransactionID pgtype.Text    `json:"transaction_id"`
}

func (q *Queries) InsertWalletRequest(ctx context.Context, arg InsertWalletRequestParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertWalletRequest,
		arg.UserID,
		arg.Amount,
		arg.UniqueAmount,
		arg.Method,
		arg.TransactionID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const listWalletRequestsAdmin = `-- name: ListWalletRequestsAdmin :many
SELECT r.id, r.user_id, u.email, r.amount, r.method, COALESCE(r.transaction_id, '')::text as transaction_id, r.status, r.created_at
FROM wallet_requests r
JOIN users u ON r.user_id = u.id
ORDER BY r.created_at DESC
`

type ListWalletRequestsAdminRow struct {
	ID            int32              `json:"id"`
	UserID        pgtype.Int4        `json:"user_id"`
	Email         pgtype.Text        `json:"email"`
	Amount        pgtype.Numeric     `json:"amount"`
	Method        string             `json:"method"`
	TransactionID string             `json:"transaction_id"`
	Status        pgtype.Text        `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListWalletRequestsAdmin(ctx context.Context) ([]ListWalletRequestsAdminRow, error) {
	rows, err := q.db.Query(ctx, listWalletRequestsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWalletRequestsAdminRow
	for rows.Next() {
		var i ListWalletRequestsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.Amount,
			&i.Method,
			&i.TransactionID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUPINotificationMatched = `-- name: MarkUPINotificationMatched :exec
UPDATE upi_notifications SET status = 'matched', matched_request_id = $1 WHERE id = $2
`

type MarkUPINotificationMatchedParams struct {
	MatchedRequestID pgtype.Int4 `json:"matched_request_id"`
	ID               int32       `json:"id"`
}

func (q *Queries) MarkUPINotificationMatched(ctx context.Context, arg MarkUPINotificationMatchedParams) error {
	_, err := q.db.Exec(ctx, markUPINotificationMatched, arg.MatchedRequestID, arg.ID)
	return err
}

const rejectWalletRequest = `-- name: RejectWalletRequest :exec
UPDATE wallet_requests SET status='rejected', updated_at=NOW() WHERE id=$1 AND status='pending'
`

func (q *Queries) RejectWalletRequest(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, rejectWalletRequest, id)
	return err
}

const updateCryptomusTransactionID = `-- name: UpdateCryptomusTransactionID :exec
UPDATE wallet_requests SET transaction_id=$1 WHERE id=$2
`

type UpdateCryptomusTransactionIDParams struct {
	TransactionID pgtype.Text `json:"transaction_id"`
	ID            int32       `json:"id"`
}

func (q *Queries) UpdateCryptomusTransactionID(ctx context.Context, arg UpdateCryptomusTransactionIDParams) error {
	_, err := q.db.Exec(ctx, updateCryptomusTransactionID, arg.TransactionID, arg.ID)
	return err
}

const updateDepositUTR = `-- name: UpdateDepositUTR :execrows
UPDATE wallet_requests SET transaction_id=$1, updated_at=NOW()
WHERE id=$2 AND user_id=$3 AND status='pending'
`

type UpdateDepositUTRParams struct {
	TransactionID pgtype.Text `json:"transaction_id"`
	ID            int32       `json:"id"`
	UserID        pgtype.Int4 `json:"user_id"`
}

func (q *Queries) UpdateDepositUTR(ctx context.Context, arg UpdateDepositUTRParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDepositUTR, arg.TransactionID, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWalletRequestStatusAndTxn = `-- name: UpdateWalletRequestStatusAndTxn :exec
UPDATE wallet_requests
SET status=$1, transaction_id=$2, updated_at=NOW()
WHERE id=$3
`

type UpdateWalletRequestStatusAndTxnParams struct {
	Status        pgtype.Text `json:"status"`
	TransactionID pgtype.Text `json:"transaction_id"`
	ID            int32       `json:"id"`
}

func (q *Queries) UpdateWalletRequestStatusAndTxn(ctx context.Context, arg UpdateWalletRequestStatusAndTxnParams) error {
	_, err := q.db.Exec(ctx, updateWalletRequestStatusAndTxn, arg.Status, arg.TransactionID, arg.ID)
	return err
}

const upsertWalletBalance = `-- name: UpsertWalletBalance :exec
INSERT INTO wallets (user_id, balance) VALUES ($1, $2)
ON CONFLICT (user_id)
DO UPDATE SET balance = wallets.balance + $2, updated_at = NOW()
`

type UpsertWalletBalanceParams struct {
	UserID  int32 `json:"user_id"`
	Balance int32 `json:"balance"`
}

func (q *Queries) UpsertWalletBalance(ctx context.Context, arg UpsertWalletBalanceParams) error {
	_, err := q.db.Exec(ctx, upsertWalletBalance, arg.UserID, arg.Balance)
	return err
}
