-- Up
ALTER TABLE orders ADD COLUMN IF NOT EXISTS remains INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS start_count INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();

-- Down
ALTER TABLE orders DROP COLUMN IF EXISTS remains;
ALTER TABLE orders DROP COLUMN IF EXISTS start_count;
ALTER TABLE orders DROP COLUMN IF EXISTS updated_at;
