import type { Metadata } from "next";
import "./style.css";
import Header from "@/components/layout/Header";
import BottomSheet from "@/components/modal/BottomSheet";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="root">
          <Header />
          {children}      
        </div>
        <BottomSheet />
      </body>
    </html>
  );
}
