import type { Metadata } from "next";
import "./style.css";
import Header from "@/components/layout/Header";
import BottomSheet from "@/components/modal/BottomSheet";
import HeaderSwitch from "@/components/layout/HeaderSwitch";
import CurrencyStrip from "@/components/layout/CurrencyStrip";
import { CurrencyProvider } from "@/components/layout/CurrencyProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="cryptomus" content="e01f06fd" />
      </head>
      <body>
        <CurrencyProvider>
          <div className="root">
            <CurrencyStrip />
            <HeaderSwitch />
            {children}
          </div>
          <BottomSheet />
        </CurrencyProvider>
      </body>
    </html>
  );
}
