import type { Metadata } from "next";
import "./style.css";
import { CurrencyProvider } from "@/components/layout/CurrencyProvider";
import RootShell from "@/components/layout/RootShell";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="cryptomus" content="e01f06fd" />
      </head>
      <body>
        <CurrencyProvider>
          <RootShell>{children}</RootShell>
        </CurrencyProvider>
      </body>
    </html>
  );
}
